# Generated by Django 4.0.3 on 2023-04-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='years_old',
        ),
    ]
